### ISSUE TITLE
App getting crash in iOS 7.

### ISSUE THREAD

**Issue by brknandhakumar** [yimingtang/TYMActivityIndicatorView#4]
App getting crash in iOS 7.
setClockwise, setHidesWhenStopped those setter methods crashing
Example app also getting crashing.
 
Crash report.
 TYMActivityIndicatorView[10581:607] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Illegal property type, c for appearance setter, _installAppearanceSwizzlesForSetter:'

**Comment by yimingtang** [comment]
`UIAppearance` proxy doesn't support `BOOL` type in iOS 7. It's fixed now.

**Comment by cameroncooke** [comment]
Can you update the Cocoapod so it points to the latest version. The current version has caused my live app to crash for all iOS 7 users.

**Comment by yimingtang** [comment]
Sorry, it's my fault. I forgot to push the spec file to CocoaPods. Now, it works.
